"""EUV exposure model — Dill ABC photoacid generation with SE blur.

Theory
------
EUV photons (13.5 nm, 91.84 eV) are absorbed by the resist according to
Beer–Lambert attenuation.  Each absorbed photon can produce multiple
photoacid molecules via the **Dill ABC model**:

    A(z)   = A₀ · exp[−(B + C · I) · z]
    M(z,t) = exp[−C · I(z) · t]              (PAC concentration)

where the three Dill parameters represent:

    A  — bleachable absorption coefficient  [1/µm]
    B  — non-bleachable absorption           [1/µm]
    C  — photo-rate constant (dose-to-acid sensitivity) [cm²/mJ]

For EUV, **secondary-electron (SE) blur** is a critical effect: photoelectrons
and Auger electrons generated by primary absorption undergo random walks
before creating photoacid, effectively blurring the aerial image.  This is
modelled as a 2D Gaussian PSF with sigma in the range 2–10 nm.

The final acid concentration is computed by convolving the blur kernel with
the local dose and multiplying by the Dill C parameter.

All operations use PyTorch tensors and are fully differentiable.

References
----------
F.H. Dill et al., "Characterization of positive photoresist",
    IEEE Trans. Electron Devices 22(7), 445–452 (1975).
R.L. Brainard et al., "Photons, electrons, and acid yields in EUV
    photoresists", J. Photopolym. Sci. Technol. 21(3), 421–428 (2008).
"""

from __future__ import annotations

from typing import Tuple

import torch
import torch.nn.functional as F

# ──────────────────────────────────────────────
# Dill ABC exposure model
# ──────────────────────────────────────────────


def dill_abc_exposure(
    dose: torch.Tensor,
    A: float | torch.Tensor = 0.5,
    B: float | torch.Tensor = 0.2,
    C: float | torch.Tensor = 0.01,
    z_positions: torch.Tensor | None = None,
    thickness: float = 0.1,
    n_layers: int = 1,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Compute Dill ABC photoacid generation.

    Models the depth-dependent absorption and photoacid generation in a
    positive-tone chemically amplified resist (CAR) during EUV exposure.

    Parameters
    ----------
    dose : torch.Tensor
        Aerial image dose in [mJ/cm²].  Shape ``(H, W)`` or ``(B, H, W)``.
    A : float or torch.Tensor
        Bleachable absorption coefficient [1/µm].  Default 0.5.
    B : float or torch.Tensor
        Non-bleachable absorption coefficient [1/µm].  Default 0.2.
    C : float or torch.Tensor
        Photo-rate constant [cm²/mJ].  Default 0.01.
    z_positions : torch.Tensor, optional
        Depth positions in [µm] along the resist thickness.  Shape ``(N,)``.
        If ``None``, ``n_layers`` equally spaced positions are used.
    thickness : float
        Total resist thickness [µm].  Default 0.1 (100 nm).
    n_layers : int
        Number of vertical layers when *z_positions* is not given.  Default 1
        (2D simulation, no depth dimension).

    Returns
    -------
    acid : torch.Tensor
        3D photoacid concentration [a.u.].  Shape ``(N, H, W)`` or
        ``(B, N, H, W)``.
    inhibitor : torch.Tensor
        Normalised inhibitor (PAC) concentration ``M(z,t)``.  Same shape as
        *acid*.  Range ``[0, 1]`` — 1 = fully inhibited, 0 = fully
        exposed.
    """
    # --- input normalisation ---
    has_batch: bool
    if dose.ndim == 2:
        dose = dose.unsqueeze(0)  # (1, H, W)
        has_batch = False
    elif dose.ndim == 3:
        has_batch = True
    else:
        raise ValueError(f"Expected 2D or 3D dose, got {dose.ndim}D")

    B, H, W = dose.shape

    # depth positions
    if z_positions is None:
        z = torch.linspace(0.0, thickness, n_layers, device=dose.device)
    else:
        z = z_positions
        n_layers = z.shape[0]

    # --- depth-dependent dose ---
    # Beer–Lambert: I(z) = I₀ · exp[−(A+B)·z]
    alpha = A + B  # total absorption [1/µm]
    dose_z = dose.unsqueeze(1) * torch.exp(-alpha * z.view(-1, 1, 1))
    # shape: (B, N, H, W)

    # --- inhibitor concentration M(z,t) ---
    inhibitor = torch.exp(-C * dose_z)

    # --- acid concentration [H⁺] ---
    acid = (1.0 - inhibitor) * A

    # restore input dims: (N, H, W) for 2D input, (B, N, H, W) for batched
    if not has_batch:
        acid = acid.squeeze(0)
        inhibitor = inhibitor.squeeze(0)

    return acid, inhibitor


# ──────────────────────────────────────────────
# Secondary-electron blur (Gaussian PSF)
# ──────────────────────────────────────────────


def gaussian_se_blur(
    image: torch.Tensor,
    sigma: float | torch.Tensor = 5.0,
    kernel_size: int | None = None,
    dx: float = 1.0,
    truncate: float = 3.0,
) -> torch.Tensor:
    """Apply secondary-electron Gaussian blur to a 2D dose/acid map.

    The SE-blur PSF is a 2D Gaussian:

        G(x, y) = (1 / 2πσ²) · exp[−(x² + y²) / (2σ²)]

    This is applied via depthwise separable convolution for efficiency.
    If the image dimensions are smaller than the kernel, sigma is reduced
    accordingly to prevent padding errors.

    Parameters
    ----------
    image : torch.Tensor
        Input tensor.  Shape ``(H, W)``, ``(B, H, W)``, or
        ``(B, C, H, W)``.  Values are assumed to be on a uniform
        spatial grid.
    sigma : float or torch.Tensor
        Gaussian sigma in grid units (nm when *dx* = 1 nm).
        Typical EUV range: 2–10 nm.  Default 5.0.
    kernel_size : int, optional
        Kernel size (odd).  Computed from *sigma* × *truncate* if
        not given.
    dx : float
        Grid spacing [nm/pixel].  Default 1.0.
    truncate : float
        Truncation radius in units of *sigma*.  Default 3.0.

    Returns
    -------
    blurred : torch.Tensor
        Blurred output, same shape as *image*.
    """
    sigma_px = sigma / dx

    if kernel_size is None:
        radius = int(truncate * sigma_px + 0.5)
        kernel_size = 2 * radius + 1
        kernel_size = max(3, kernel_size)

    if kernel_size % 2 == 0:
        kernel_size += 1

    # --- convert to 4D and check dimensions ---
    orig_ndim = image.ndim
    if orig_ndim == 2:
        img_4d = image.unsqueeze(0).unsqueeze(0)  # (1, 1, H, W)
    elif orig_ndim == 3:
        img_4d = image.unsqueeze(1)  # (B, 1, H, W)
    else:
        img_4d = image

    B, C, H, W = img_4d.shape

    # Clamp kernel_size to be no larger than image dimensions
    max_dim = min(H, W)
    if kernel_size > max_dim:
        kernel_size = max_dim if max_dim % 2 == 1 else max_dim - 1
        kernel_size = max(3, kernel_size)

    # --- build 1D Gaussian kernel ---
    radius = kernel_size // 2
    # Match input dtype — F.conv2d requires kernel and input to have the same dtype
    working_dtype = image.dtype
    x = torch.arange(-radius, radius + 1, device=image.device, dtype=working_dtype)
    kernel_1d = torch.exp(-0.5 * (x / sigma_px) ** 2)
    kernel_1d = kernel_1d / (kernel_1d.sum() + 1e-12)

    # separable convolution
    col_k = kernel_1d.view(1, 1, kernel_size, 1).repeat(C, 1, 1, 1)
    row_k = kernel_1d.view(1, 1, 1, kernel_size).repeat(C, 1, 1, 1)

    pad_col = F.pad(img_4d, (0, 0, radius, radius), mode="reflect")
    blurred = F.conv2d(pad_col, col_k, groups=C)

    pad_row = F.pad(blurred, (radius, radius, 0, 0), mode="reflect")
    blurred = F.conv2d(pad_row, row_k, groups=C)

    # restore input shape
    if orig_ndim == 2:
        blurred = blurred.squeeze(0).squeeze(0)
    elif orig_ndim == 3:
        blurred = blurred.squeeze(1)

    return blurred


# ──────────────────────────────────────────────
# Dose-to-acid mapping
# ──────────────────────────────────────────────


def dose_to_acid(
    dose: torch.Tensor,
    C: float | torch.Tensor = 0.01,
    Q: float | torch.Tensor = 0.04,
    sigma_blur: float | torch.Tensor = 5.0,
    dx: float = 1.0,
    apply_blur: bool = True,
) -> torch.Tensor:
    """Map EUV dose to photoacid concentration.

    This is a simplified end-to-end dose-to-acid pipeline:

        1. Apply secondary-electron Gaussian blur to the dose map.
        2. Convert to photoacid concentration: ``[H⁺] = Q · (1 − exp[−C ·
        dose])``

    where *Q* is the maximum acid yield and *C* is the Dill C parameter.

    Parameters
    ----------
    dose : torch.Tensor
        Input dose map [mJ/cm²].  Shape ``(H, W)`` or ``(B, H, W)``.
    C : float or torch.Tensor
        Photo-rate constant [cm²/mJ].  Default 0.01.
    Q : float or torch.Tensor
        Quantum efficiency — maximum acid molecules per absorbed
        photon.  Default 0.04 (typical for EUV CAR).
    sigma_blur : float or torch.Tensor
        Secondary-electron blur sigma [nm].  Default 5.0.
    dx : float
        Grid spacing [nm/pixel].  Default 1.0.
    apply_blur : bool
        Whether to apply SE blur.  Default ``True``.

    Returns
    -------
    acid : torch.Tensor
        Photoacid concentration.  Same shape as *dose*.
    """
    if apply_blur:
        dose_blurred = gaussian_se_blur(dose, sigma=sigma_blur, dx=dx)
    else:
        dose_blurred = dose

    acid = Q * (1.0 - torch.exp(-C * dose_blurred))
    return acid
