"""EUV exposure model — Dill ABC photoacid generation with SE blur.

Theory
------
EUV photons (13.5 nm, 91.84 eV / photon) are absorbed by the resist according to
Beer–Lambert attenuation.  Each absorbed photon can produce multiple
photoacid molecules via the **Dill ABC model**:

    A(z)   = A₀ · exp[−(B + C · I) · z]
    M(z,t) = exp[−C · I(z) · t]              (PAC concentration)

where the three Dill parameters represent:

    A  — bleachable absorption coefficient  [1/µm]
    B  — non-bleachable absorption           [1/µm]
    C  — photo-rate constant (dose-to-acid sensitivity) [cm²/mJ]

For EUV, **secondary-electron (SE) blur** is a critical effect: photoelectrons
and Auger electrons generated by primary absorption undergo random walks
before creating photoacid, effectively blurring the aerial image.  This is
modelled as a 2D Gaussian PSF with sigma in the range 2–10 nm.

The final acid concentration is computed by convolving the blur kernel with
the local dose and multiplying by the Dill C parameter.

All operations use PyTorch tensors and are fully differentiable.

References
----------
F.H. Dill et al., "Characterization of positive photoresist",
    IEEE Trans. Electron Devices 22(7), 445–452 (1975).
R.L. Brainard et al., "Photons, electrons, and acid yields in EUV
    photoresists", J. Photopolym. Sci. Technol. 21(3), 421–428 (2008).

Note on photon energy: The default 13.5 nm wavelength corresponds to
~91.84 eV (CXRO grid point). Use the derived energy from wavelength
(E = hc/λ) for consistency across the simulation pipeline.
"""

from __future__ import annotations

from typing import Tuple

import torch
import torch.nn.functional as F

# ──────────────────────────────────────────────
# Dill ABC exposure model
# ──────────────────────────────────────────────


def dill_abc_exposure(
    dose: torch.Tensor,
    A: float | torch.Tensor = 0.5,
    B: float | torch.Tensor = 0.2,
    C: float | torch.Tensor = 0.1,
    z_positions: torch.Tensor | None = None,
    thickness: float = 0.1,
    n_layers: int = 1,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Compute Dill ABC photoacid generation.

    Models the depth-dependent absorption and photoacid generation in a
    positive-tone chemically amplified resist (CAR) during EUV exposure.

    Parameters
    ----------
    dose : torch.Tensor
        Aerial image dose in [mJ/cm²].  Shape ``(H, W)`` or ``(B, H, W)``.
    A : float or torch.Tensor
        Bleachable absorption coefficient [1/µm].  Default 0.5.
    B : float or torch.Tensor
        Non-bleachable absorption coefficient [1/µm].  Default 0.2.
    C : float or torch.Tensor
        Photo-rate constant [cm²/mJ]. In an EUV CAR it already contains the
        PAG quantum efficiency (Mack 2013, "Stochastic exposure kinetics of
        EUV photoresists: Trapping model", Eq. 8: C ∝ φ_PAG·σ·…), so the
        acid yield is 1 − exp(−C·E) with no separate prefactor (Eq. 10).
        A former ``Q`` argument that multiplied this yield double-counted
        φ_PAG and was removed 2026-09-04.
    z_positions : torch.Tensor, optional
        Depth positions in [µm] along the resist thickness.  Shape ``(N,)``.
        If ``None``, ``n_layers`` equally spaced positions are used.
    thickness : float
        Total resist thickness [µm].  Default 0.1 (100 nm).
    n_layers : int
        Number of vertical layers when *z_positions* is not given.  Default 1
        (2D simulation, no depth dimension).

    Returns
    -------
    acid : torch.Tensor
        3D photoacid concentration [a.u.].  Shape ``(N, H, W)`` or
        ``(B, N, H, W)``.
    inhibitor : torch.Tensor
        Normalised inhibitor (PAC) concentration ``M(z,t)``.  Same shape as
        *acid*.  Range ``[0, 1]`` — 1 = fully inhibited, 0 = fully
        exposed.
    """
    # --- input normalisation ---
    has_batch: bool
    if dose.ndim == 2:
        dose = dose.unsqueeze(0)  # (1, H, W)
        has_batch = False
    elif dose.ndim == 3:
        has_batch = True
    else:
        raise ValueError(f"Expected 2D or 3D dose, got {dose.ndim}D")

    # NOTE: do not unpack the batch size into a variable named ``B`` -- that
    # is the Dill B parameter. Before 2026-09-04 this line read
    # ``B, H, W = dose.shape``, silently replacing dill_B by the batch size
    # (1 for a 2D dose map), so the absorption coefficient was A + 1.0 µm⁻¹
    # regardless of the configured dill_B. Found by
    # tests/test_photon_absorption.py::test_absorbed_fraction_uses_same_coefficient_as_depth_profile.
    n_batch, H, W = dose.shape

    # depth positions
    if z_positions is None:
        z = torch.linspace(0.0, thickness, n_layers, device=dose.device)
    else:
        z = z_positions
        n_layers = z.shape[0]

    # --- depth-dependent dose ---
    # Beer–Lambert: I(z) = I₀ · exp[−(A+B)·z]
    alpha = A + B  # total absorption [1/µm]
    dose_z = dose.unsqueeze(1) * torch.exp(-alpha * z.view(-1, 1, 1))
    # shape: (B, N, H, W)

    # --- inhibitor concentration M(z,t) ---
    inhibitor = torch.exp(-C * dose_z)

    # --- acid concentration [H⁺] relative to the initial PAG density ---
    # acid = 1 - M: the fraction of PAG converted (Mack 2013, Eq. 10).
    # A is the bleachable absorption coefficient (1/µm), NOT a concentration.
    acid = 1.0 - inhibitor

    # restore input dims: (N, H, W) for 2D input, (B, N, H, W) for batched
    if not has_batch:
        acid = acid.squeeze(0)
        inhibitor = inhibitor.squeeze(0)

    return acid, inhibitor


# ──────────────────────────────────────────────
# PAG/quencher molecular discreteness (stochastic exposure)
# ──────────────────────────────────────────────


def sample_pag_quencher_acid(
    dose_z: torch.Tensor,
    C: float | torch.Tensor,
    pag_density: float,
    quencher_density: float,
    dx: float,
    dz: float,
    dy: float | None = None,
    rng: torch.Generator | None = None,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Sample discrete PAG/quencher acid generation (molecular shot noise).

    ``dill_abc_exposure`` computes the MEAN-FIELD acid
    concentration, ``acid = 1-exp(-C*dose)`` -- correct in the limit
    of infinitely many PAG molecules per voxel, but EUV lithography's
    whole "stochastics problem" is that a real voxel does not have
    infinitely many: a 92 eV photon absorption event converts one of a
    FINITE, LOCALLY-COUNTED number of PAG molecules, and that finiteness
    is itself a noise source distinct from (and, per the validation in
    docs/claude_code_arbeitslog.md 2026-09-03, apparently LARGER than)
    photon-arrival shot noise alone. This function samples that finite-
    population effect directly:

        n_PAG ~ Poisson(rho_PAG * V_voxel)          -- molecules actually
                                                          present, not just
                                                          their mean
        p_convert = 1 - exp(-C * dose_z)           -- same Dill-C
                                                          conversion
                                                          probability as
                                                          the mean-field
                                                          model (phi_PAG
                                                          is inside C)
        n_acid ~ Binomial(n_PAG, p_convert)          -- each present PAG
                                                          independently
                                                          converts or not;
                                                          saturation
                                                          (can't exceed
                                                          n_PAG) is free
        n_Q ~ Poisson(rho_Q * V_voxel)               -- quencher loaded
                                                          independently of
                                                          exposure

    Both outputs are normalised to rho_PAG (i.e. acid=1 would mean "every
    PAG in this voxel's average population converted"), matching this
    codebase's existing acid-concentration convention and the h=H/G0,
    q=Q/G0 relative-concentration convention used by the PEB quenching
    step below (see peb.py's ``reaction_diffusion_with_quenching``).

    Parameters
    ----------
    dose_z : torch.Tensor
        Depth-resolved dose after Beer-Lambert attenuation [mJ/cm²] (the
        same quantity ``dill_abc_exposure`` computes internally before
        its own mean-field acid step). Shape ``(N, H, W)`` or ``(H, W)``.
    C : float or torch.Tensor
        Dill photo-rate constant [cm²/mJ] -- same parameter and same
        physical role as in the mean-field model.
    pag_density : float
        Initial PAG number density [nm⁻³]. Real, cited EUV-native value:
        Mack, Biafore & Smith, "Stochastic Acid-Base Quenching in
        Chemically Amplified Photoresists: A Simulation Study," Proc.
        SPIE 7972, 797202 (2011), Table I ("Baseline stochastic resist
        parameters for EUV simulations") -- free via lithoguru.com. See
        pipeline.py's pag_density_per_nm3 comment for the full citation.
    quencher_density : float
        Initial quencher number density [nm⁻³]. Same source/table.
    dx, dz : float
        Lateral and vertical voxel dimensions [nm].
    dy : float, optional
        Second lateral voxel dimension [nm]. Defaults to *dx* (matches
        ``photon_deposition_shot_noise``'s own convention -- this
        codebase's lateral grid is a 1D line/space cross-section
        Y-tiled for statistics, so *dy* is a real physical voxel extent
        along the un-modelled direction, not merely 1).
    rng : torch.Generator, optional
        RNG for the Poisson/Binomial draws. A fresh (non-reproducible)
        CPU generator is created if not given.

    Returns
    -------
    acid : torch.Tensor
        Sampled relative acid concentration, same shape as *dose_z*.
    quencher : torch.Tensor
        Sampled relative quencher concentration, same shape as *dose_z*.
    """
    if rng is None:
        rng = torch.Generator(device=dose_z.device)

    dy_val = dy if dy is not None else dx
    voxel_volume = dx * dy_val * dz
    mean_pag = max(pag_density * voxel_volume, 1e-12)
    mean_quencher = quencher_density * voxel_volume

    n_pag = torch.poisson(torch.full_like(dose_z, mean_pag), generator=rng)
    p_convert = torch.clamp(1.0 - torch.exp(-C * dose_z), 0.0, 1.0)
    n_acid = torch.binomial(n_pag, p_convert, generator=rng) if hasattr(torch, "binomial") else _binomial_fallback(n_pag, p_convert, rng)
    n_quencher = torch.poisson(torch.full_like(dose_z, mean_quencher), generator=rng)

    acid = n_acid / mean_pag
    quencher = n_quencher / mean_pag

    return acid, quencher


def _binomial_fallback(
    n: torch.Tensor, p: torch.Tensor, rng: torch.Generator
) -> torch.Tensor:
    """Binomial(n, p) via a normal approximation with continuity correction.

    Only used if the installed torch build lacks ``torch.binomial``
    (added in a relatively recent torch release). np*(1-p) is large
    enough at EUV-relevant PAG densities (typically several molecules
    per voxel at the grid resolutions this codebase uses) that the
    normal approximation is adequate; rounded and clamped to [0, n].
    """
    mean = n * p
    var = torch.clamp(n * p * (1.0 - p), min=1e-12)
    draw = torch.normal(mean, var.sqrt(), generator=rng)
    return torch.clamp(torch.round(draw), min=torch.zeros_like(n), max=n)


# ──────────────────────────────────────────────
# Secondary-electron blur (Gaussian PSF)
# ──────────────────────────────────────────────


def _fft_circular_blur(
    img_4d: torch.Tensor, kernel_1d: torch.Tensor, radius: int, H: int, W: int
) -> torch.Tensor:
    """FFT-based 2D circular convolution with a separable Gaussian kernel.

    Mathematically identical to two circularly-padded 1D conv2d passes
    (row then column) with the outer-product kernel ``kernel_1d ⊗
    kernel_1d`` -- both compute the same periodic/circular convolution,
    just via a different algorithm (O(H*W*log(H*W)) here instead of
    O(H*W*kernel_size)). Used by :func:`gaussian_se_blur` for large
    kernels where the direct path is prohibitively slow (see its call
    site for why this matters and how it was validated).

    Parameters
    ----------
    img_4d : torch.Tensor
        Input, shape ``(B, C, H, W)``.
    kernel_1d : torch.Tensor
        Normalised 1D Gaussian, length ``2*radius + 1``.
    radius : int
        ``(len(kernel_1d) - 1) // 2``.
    H, W : int
        Spatial dimensions of *img_4d* (passed explicitly to avoid
        re-deriving them from the tensor at every call).

    Returns
    -------
    blurred : torch.Tensor
        Same shape as *img_4d*.
    """
    kernel_2d = torch.outer(kernel_1d, kernel_1d)  # (k, k), k = 2*radius+1
    offsets = torch.arange(-radius, radius + 1, device=img_4d.device)
    row_idx = offsets % H
    col_idx = offsets % W
    kernel_padded = torch.zeros(H, W, dtype=img_4d.dtype, device=img_4d.device)
    # ACCUMULATE: when the kernel is wider than the (periodic) image, several
    # taps wrap onto the same cell; plain assignment would keep only the
    # last one. Accumulation is exactly the periodic summation of the
    # kernel, which is what a circular convolution with a wide kernel is.
    k = kernel_2d.shape[0]
    kernel_padded.index_put_(
        (row_idx.unsqueeze(1).expand(k, k), col_idx.unsqueeze(0).expand(k, k)),
        kernel_2d,
        accumulate=True,
    )

    K = torch.fft.rfft2(kernel_padded)
    X = torch.fft.rfft2(img_4d, dim=(-2, -1))
    return torch.fft.irfft2(X * K, s=(H, W), dim=(-2, -1))


def gaussian_se_blur(
    image: torch.Tensor,
    sigma: float | torch.Tensor = 5.0,
    kernel_size: int | None = None,
    dx: float = 1.0,
    truncate: float = 4.0,
) -> torch.Tensor:
    """Apply secondary-electron Gaussian blur to a 2D dose/acid map.

    The SE-blur PSF is a 2D Gaussian:

        G(x, y) = (1 / 2πσ²) · exp[−(x² + y²) / (2σ²)]

    This is applied via depthwise separable convolution for small kernels
    and via an exact circular (FFT) convolution for kernels larger than
    64 px or than the image in either axis. The image is treated as
    periodic in both axes (one pitch in x, the Y-tiled field in y).

    Parameters
    ----------
    image : torch.Tensor
        Input tensor.  Shape ``(H, W)``, ``(B, H, W)``, or
        ``(B, C, H, W)``.  Values are assumed to be on a uniform
        spatial grid.
    sigma : float or torch.Tensor
        Gaussian sigma in grid units (nm when *dx* = 1 nm).
        Typical EUV range: 2–10 nm.  Default 5.0.
    kernel_size : int, optional
        Kernel size (odd).  Computed from *sigma* × *truncate* if
        not given.
    dx : float
        Grid spacing [nm/pixel].  Default 1.0.
    truncate : float
        Truncation radius in units of *sigma*.  Default 4.0 (2026-09-04;
        was 3.0): a 3σ-truncated, renormalised kernel carries 0.27 % of its
        mass in the cut tails and overstates the modulation transfer at the
        pitch frequency by ~0.5 %; at 4σ the error is ~1e-4. The cost is
        irrelevant on the FFT path.

    Returns
    -------
    blurred : torch.Tensor
        Blurred output, same shape as *image*.
    """
    sigma_px = sigma / dx

    # Handle sigma = 0 (no blur) as a special case
    if sigma_px < 1e-12:
        return image

    if kernel_size is None:
        radius = int(truncate * sigma_px + 0.5)
        kernel_size = 2 * radius + 1
        kernel_size = max(3, kernel_size)

    if kernel_size % 2 == 0:
        kernel_size += 1

    # --- convert to 4D and check dimensions ---
    orig_ndim = image.ndim
    if orig_ndim == 2:
        img_4d = image.unsqueeze(0).unsqueeze(0)  # (1, 1, H, W)
    elif orig_ndim == 3:
        img_4d = image.unsqueeze(1)  # (B, 1, H, W)
    else:
        img_4d = image

    B, C, H, W = img_4d.shape

    # NO clamping of the kernel to the image size. Until 2026-09-04 the
    # kernel was cut to min(H, W) (= 255 px for the 256-px pitch grid): a
    # PEB blur of σ = 19.9 nm at dx = 0.17 nm (695-px kernel) was truncated
    # at ±1.1σ and renormalised, i.e. it was not a Gaussian any more -- its
    # MTF at the pitch frequency was 0.12 instead of exp(−2π²σ²/P²) = 0.018
    # (6.9× too much contrast; 1.7× at σ = 14 nm, 1.09× at 10 nm). The
    # image is periodic in both axes (one pitch in x, the Y-tiled field in
    # y), so the exact operation for ANY kernel size is the circular
    # convolution, which the FFT path below computes with wrapped taps
    # accumulated (tests/test_blur.py pins the analytic MTF).

    # --- build 1D Gaussian kernel ---
    radius = kernel_size // 2
    # Match input dtype — F.conv2d requires kernel and input to have the same dtype
    working_dtype = image.dtype
    x = torch.arange(-radius, radius + 1, device=image.device, dtype=working_dtype)
    kernel_1d = torch.exp(-0.5 * (x / sigma_px) ** 2)
    kernel_1d = kernel_1d / (kernel_1d.sum() + 1e-12)

    # For large kernels (large sigma and/or many depth layers/rows batched
    # through B), direct separable conv2d becomes the bottleneck: cost
    # scales as B*C*H*W*kernel_size per pass. FFT-based circular
    # convolution costs O(B*C*H*W*log(H*W)) instead, independent of kernel
    # size, and computes the EXACT SAME mathematical operation (periodic/
    # circular convolution with the same separable kernel, since the
    # existing direct path already pads circularly) -- not an
    # approximation, just a faster algorithm for it. Threshold chosen so
    # every kernel size exercised by this module's existing test suite
    # (typically <=31, occasionally ~121 for SE-blur at fine dx) still
    # takes the original path unchanged; only genuinely large kernels
    # (e.g. PEB diffusion blur, sigma~20nm at fine dx -> kernel~250+,
    # multiplied by many depth layers/tiled rows in the stochastic LER
    # path) route through FFT. Verified empirically (not just claimed) to
    # agree with the direct path to float32 precision on representative
    # inputs before this was adopted -- see docs/claude_code_arbeitslog.md.
    if kernel_size > 64 or kernel_size > min(H, W):
        # One image at a time: each (H, W) plane is an independent circular
        # convolution, so the result is identical, but the complex128 FFT
        # intermediates (~6x the plane) are no longer allocated for the whole
        # (N, H, W) stack at once -- the 61440-row LER fields exceeded 8 GB
        # here (2026-09-05).
        blurred = torch.cat(
            [_fft_circular_blur(img_4d[b : b + 1], kernel_1d, radius, H, W) for b in range(B)], dim=0
        )
    else:
        # separable convolution
        col_k = kernel_1d.view(1, 1, kernel_size, 1).repeat(C, 1, 1, 1)
        row_k = kernel_1d.view(1, 1, 1, kernel_size).repeat(C, 1, 1, 1)

        pad_col = F.pad(img_4d, (0, 0, radius, radius), mode="circular")
        blurred = F.conv2d(pad_col, col_k, groups=C)

        pad_row = F.pad(blurred, (radius, radius, 0, 0), mode="circular")
        blurred = F.conv2d(pad_row, row_k, groups=C)

    # restore input shape
    if orig_ndim == 2:
        blurred = blurred.squeeze(0).squeeze(0)
    elif orig_ndim == 3:
        blurred = blurred.squeeze(1)

    return blurred


# ──────────────────────────────────────────────
# Dose-to-acid mapping
# ──────────────────────────────────────────────


def dose_to_acid(
    dose: torch.Tensor,
    C: float | torch.Tensor = 0.1,
    Q: float | torch.Tensor = 0.04,
    sigma_blur: float | torch.Tensor = 5.0,
    dx: float = 1.0,
    apply_blur: bool = True,
) -> torch.Tensor:
    """Map EUV dose to photoacid concentration.

    This is a simplified end-to-end dose-to-acid pipeline:

        1. Apply secondary-electron Gaussian blur to the dose map.
        2. Convert to photoacid concentration: ``[H⁺] = Q · (1 − exp[−C · dose])``

    where *Q* is the maximum acid yield and *C* is the Dill C parameter.

    Parameters
    ----------
    dose : torch.Tensor
        Input dose map [mJ/cm²].  Shape ``(H, W)`` or ``(B, H, W)``.
    C : float or torch.Tensor
        Photo-rate constant [cm²/mJ].  Default 0.1 (realistic for EUV CAR).
    Q : float or torch.Tensor
        Quantum efficiency — maximum acid molecules per absorbed
        photon.  Default 0.04 (typical for EUV CAR in simplified model).
        The full dill_abc_exposure uses Q=0.1 with explicit depth-dependent
        absorption; the simplified model uses lower Q to account for
        average depth absorption.
    sigma_blur : float or torch.Tensor
        Secondary-electron blur sigma [nm].  Default 5.0.
    dx : float
        Grid spacing [nm/pixel].  Default 1.0.
    apply_blur : bool
        Whether to apply SE blur.  Default ``True``.

    Returns
    -------
    acid : torch.Tensor
        Photoacid concentration.  Same shape as *dose*.
    """
    if apply_blur:
        dose_blurred = gaussian_se_blur(dose, sigma=sigma_blur, dx=dx)
    else:
        dose_blurred = dose

    acid = Q * (1.0 - torch.exp(-C * dose_blurred))
    return acid
